mongo: {}
documentdb:
  database: treeherder-proxy

treeherder:
  apiUrl: https://treeherder.mozilla.org/api/

treeherderActions:
  routePrefix: taskcluster
  prefetch: 200

taskcluster:
  credentials: {}

treeherderTaskcluster:
  routePrefix: tc-treeherder
  prefetch: 200

treeherderProxy:
  port: 60025

config: {}
pulse: {}

kue:
  logFailedJobs: false
  admin:
    port: 60024

repositoryMonitor:
  interval: 10000
  maxPushFetches: 200

commitPublisher:
  title: |
    Pushlog Commit Events
  description: |
    The pushlog events can be used to hook various other components into
    the act of commiting to a particuar repository (usually to kick off tests)
    this exchange is hopefuly a short lived thing which abstracts polling the
    pushlog for new data.

    Pushes will be monitored (via polling) and events will be sent as new data
    is available. If for some reason the service goes down previous commits
    will also be fetched and any missing data (up to a particular amount) will
    be sent as events...

# Nobody's quite sure why this is called try.  Don't be confused!  It includes all
# projects, not just try.
try:
  enabled: true

  # This is the preferred location for the decision task file for every repository.
  # Mustache parameters used to customize the path:
  #
  #   - alias: current key name
  #   - revision: revision of the change
  #   - path: sub path to repository
  #   - host: host of repository
  #
  tcYamlUrl: "{{{host}}}{{{path}}}/raw-file/{{revision}}/.taskcluster.yml"

  # Default url used when figuring out where to fetch task graph has some special
  defaultUrl: "{{{host}}}{{{path}}}/raw-file/{{revision}}/testing/taskcluster/tasks/decision/branch.yml"

  # If for some reason the task yaml is invalid we still would like to create a
  # task if for no other reason than to notify the user that this failed.  Note that this
  # is a YAML string embedded in YAML.
  errorTask: |
    version: 0
    metadata:
      name: 'Error Message Task'
      description: |
        There was an error creating the decision task.
      owner: "{{owner}}"
      source: "{{{source}}}"

    tasks:
      - taskId: '{{#as_slugid}}decision-task{{/as_slugid}}'
        task:
          created: '{{now}}'
          deadline: '{{#from_now }}5 minutes{{/from_now}}'
          metadata:
            source: '{{{source}}}'
            owner: '{{owner}}'
            name: Error message...
            description: |
              Error creating decision task...

          workerType: gecko-decision
          provisionerId: aws-provisioner-v1
          routes:
             - "tc-treeherder-stage.{{project}}.{{revision_hash}}"
             - "tc-treeherder.{{project}}.{{revision_hash}}"
          payload:
            image: 'quay.io/mozilla/decision:0.0.3'
            maxRunTime: 500
            command:
              - /bin/bash
              - -c
              - >
                echo "[taskcluster:error] ERROR Generating task graph (no tests/build will be created)";
                echo "[taskcluster:error] $ERROR_MSG";
                exit 1
          extra:
            treeherder:
              symbol: D

  # Each project can have
  #  - url: url of the decision task YAML (defaults to defaultUrl)
  #  - scopes: scopes for the task graph
  #  - level: SCM level (defaults to 1) passed to the decision task
  projects:
    # Note that most of this data is loaded from the projectsYmlUrl.
    # These are non-gecko, legacy projects that are not included there.
    bmo-master:
      scopes:
        - "assume:repo:github.com/mozilla/webtools-bmo-bugzilla:*"

    ci-admin:
      level: 3
      scopes:
        - "assume:repo:hg.mozilla.org/build/ci-admin:*"

    ci-configuration:
      level: 3
      scopes:
        - "assume:repo:hg.mozilla.org/build/ci-configuration:*"

    nss:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/automation/taskcluster/decision_task.yml"
      level: 'nss'
      scopes:
        - "assume:repo:hg.mozilla.org/projects/nss:*"
        
    nss-try:
      url: "{{{host}}}{{{path}}}/raw-file/{{revision}}/automation/taskcluster/decision_task.yml"
      level: 'nss-try'
      scopes:
        - "assume:repo:hg.mozilla.org/projects/nss-try:*"

    # This has a repository entry in the DB that was created manually. When this is removed,
    # the database entry should be removed as well.
    users/mozilla_hocat.ca/comm-taskcluster:
      level: 1
      scopes:
        - "assume:repo:hg.mozilla.org/users/mozilla_hocat.ca/comm-taskcluster:*"
